baseurl: /premium
port: 4000
destination: ./_dev
github: [metadata]
encoding: UTF-8
kramdown:
 input: GFM
 hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
collections:
  lessons:
    output: true
  pages:
    output: true
include: ['.htaccess']
exclude: [not-in-git, node_modules, artwork, csv_to_html, 
        "_lessons/class2vn",
        "_lessons/class1en",
        "_lessons/class2en",
        "_lessons/class1pt",
        "_lessons/class2pt"
        ]
trialdeploy: false
upgrade_pt: https://get.englishletics.com/
upgrade_vn: https://get.englishletics.com/nguoi-su-dung-phien-ban-cao-cap-hoc-tieng-anh-nhanh-va-hieu-qua-hon/?lang=vi
upgrade_en: https://get.englishletics.com/people-going-premium-learn-english-faster-and-better/


page_gen:
  - index_files: false
    data: api 
    template: api_free
    name: current_lesson_compound
    dir: api_free
    extension: json
  - index_files: false
    data: api 
    template: api_premium
    name: current_lesson_compound
    dir: api_premium
    extension: json


