baseurl: /dev
incremental: true
port: 4044
destination: ./_dev
github: [metadata]
encoding: UTF-8
kramdown:
 input: GFM
 hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
collections:
  lessons:
    output: true
  pages:
    output: true
include: ['.htaccess']
exclude: [not-in-git, node_modules, gulpfile.js, artwork, csv_to_html, 
        "_lessons/class1en/*",
        "_lessons/class2en",
        "_lessons/class1pt/",
        "_lessons/class2pt",
        "_lessons/class1vn/lesson2*",
        "_lessons/class2vn/"
        ]
trialdeploy: true

texts:
  vn:
    upgrade_url: https://get.englishletics.com/?add-to-cart=71&chatfuelid=MYCHATFUELID
    salespage_url: https://get.englishletics.com/en/people-going-premium-learn-english-faster-and-better/?chatfuelid=MYCHATFUELID
  pt:
    upgrade_url: https://get.englishletics.com/pt-br/?add-to-cart=70&chatfuelid=MYCHATFUELID
    salespage_url: https://get.englishletics.com/en/people-going-premium-learn-english-faster-and-better/?chatfuelid=MYCHATFUELID
  en:
    upgrade_url: https://get.englishletics.com/en/?add-to-cart=8&chatfuelid=MYCHATFUELID
    salespage_url: https://get.englishletics.com/en/people-going-premium-learn-english-faster-and-better/?chatfuelid=MYCHATFUELID


